### PR TITLE
Fixes PHPCS Reports

### PR DESCRIPTION
**Pull request by elisei**
Hi @ManaLight 

I'm submitting this PR for minor fixes reported in the PHP Code Sniffer analysis with a severity level of 1.

I also added issue templates and actions for continuous PHPCS analysis

### CODE REVIEW

**Comment by ManaLight** [comment]
@elisei Thank you very much for your work! I will check it soon.

**Comment by ManaLight** [comment]
@elisei I have some questions.

1. I see that there are some unrelated files: ```.codeclimate.yml```, ```.scrutinizer.yml```, and ```composer.lock``` with many dependencies (```colinmollenhour/credis```, ...). Do you think we need them?

2. ```composer.json``` has ```"magento/framework": "~103"``` (Magento 2.4+) but I think we shouldn't define a version constrain for ```magento/framework``` . The extension is designed to work with any Magento 2 version. Because Magento marketplace doesn't allow the old syntax for Setup scripts, I had to change them to Data patch, which makes only Magento 2.3+ and Magento 2.4+ are supported.

3. In ```\PureMashiro\BundleJs\Action\Collect\AddRequireJsContextsConfig::execute```, ```@param string $dom``` should be ```\simple_html_dom\simple_html_dom $dom```

```
    /**
     * Execute.
     *
     * @param \simple_html_dom\simple_html_dom $dom
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function execute($dom)
```

**Comment by elisei** [comment]
@ManaLight 

1 - The composer.lock you already need, the others I will send a future pull request for them! =)

2 - I need a proper declaration of the minimum stable version for each component. By default, we shouldn't even call it a "framework," but I still don't know the project in depth, so I'm not aware of its real dependencies. Just an observation, supporting 2.3+ is good, but anything lower than that is really restrictive in terms of what can be done with the code in the future...

3 - Alright, I'll fix it!

**Comment by ManaLight** [comment]
@elisei 

1. I still think we don't need these files. It is up to the dev to decide which files they use and we shouldn't add them by default.
2. ```"magento/framework": "~102|~103"``` is good as well.
3. Thank you!
4. Btw, I have merged release/1.3.3 into the master branch to fix the issue in https://github.com/ManaLight/magento2-bundlejs/issues/2, so there will be some conflicts. Please help me resolve them. Thank you

**Comment by ManaLight** [comment]
@elisei Thank you for your works!

I see that composer.lock is included in the extension. I'm worried that composer.lock of the extension can cause conflict with the root composer.lock of some projects. Can we remove it?

Thank you.

**Comment by elisei** [comment]
Hi @ManaLight 

There won't be any conflict, composer.lock is used to expedite code auditing processes for external code, or even for unit tests.

Currently, I use them in several projects, some of which are also approved by Adobe:
https://github.com/pagseguro/payment-magento/blob/Magento%402.4.6/composer.lock -> https://commercemarketplace.adobe.com/pagbank-payment.html
https://github.com/Getnet-Brasil/payment-magento/blob/Magento%402.4/composer.lock -> https://commercemarketplace.adobe.com/getnet-payment.html

And many others, although not uploaded to the Adobe Marketplace, are fully functional:
https://github.com/elisei/full-checkout/blob/Magento%402.4/composer.lock

**Comment by ManaLight** [comment]
Hi @elisei, I've tested and see that composer.lock of the extension has no affect composer.lock of the project, so it is fine to have the composer.lock in the extension. Thank you.

**Comment by elisei** [comment]
@ManaLight 
Do you have any idea when you will publish this? I'm about to release updates and I want to take advantage of it.

**Comment by ManaLight** [comment]
@elisei PHPCS was merged to 1.3.4-alpha1 (not master though). I will check PHPMD later today and merge them at once. Thank you for your patience.

**Pull request merged**
